### PR TITLE
Code Cleanup work

### PR DESCRIPTION
**Pull request by HalosGhost**
If you are not interested in accepting PRs, just let me know. However, if you are interested in taking PRs, do not merge this just yet, there is still more I would like to do to clean up the code, and it is not yet stable.

So far, the PR includes the following:
- No dramatic changes to code style (e.g., bracing, indentation, etc) in an attempt to avoid cosmetic changes
- No API changes (this is just meant to be cleanup/optimization)
- Try to be as fast as possible (`!x` is faster than `x==NULL` but is logically equivalent)
- Be consistent with types where possible (e.g., `sizeof` returns `size_t`, so when comparing it, you should use `size_t` instead of `int`)

### CODE REVIEW

**Comment by sdhand** [comment]
I'm certainly interested in pull requests, and thanks very much for cleaning up my (rather poor) code. The one change I'd take minor issue with is the assignment change on the struct array in x11fs.c as this was originally designed to make the structure of the file hierarchy clear. However your way obviously makes it easier to tell which field is which, so maybe it's for the best. Other than that, please tell me when this is ready to be merged, thanks once again.

**Comment by HalosGhost** [comment]
Sounds good! I will keep on cleaning things up (after this PR is closed, if you are interested, I may also look into adding better error handling which may involve an API change).

As for the struct array, I figured that was your intention (and that was the only cosmetic change I made really), but it made it dramatically more difficult to read. Plus, since the hierarchy is actually specified in the first field anyway, I do not feel that the visual alignment helped much.

However, this is your project; you are, of course, free to cherry pick commits that you like of mine!

**Comment by HalosGhost** [comment]
All right; we are approaching completion. My tests suggest it is relatively stable (with obvious bits of breakage having been fixed). I want to walk through `win_xcb.c` a bit more to see if I can clean any of it up a bit more; but once that is done, I think it will be ready for merge.

However, I would strongly suggest, since there is no comprehensive test suite, that you personally test from my branch to see that it still works as you expect. If not, let me know and I'll look into fixing whatever you'd like.

**Comment by HarveyHunt** [comment]
The mapping of event -> struct is as follows:
- Create: `xcb_create_notify_event_t`
- Destroy: `xcb_destroy_notify_event_t`
- Enter: `xcb_enter_notify_event_t`
- Leave: `xcb_leave_notify_event_t`
- Map: `xcb_map_notify_event_t`
- Unmap: `xcb_unmap_notify_event_t`

Although enter and leave are identical structs, it's better to be clear though. :-)

**Comment by sdhand** [comment]
Thanks for the warning. I guess the ones I was using previously were similar enough to not cause problems, but as you say, better to be clear.

**Comment by halfwit** [comment]
I've been on HalosGhosts branch for a few days now, it's been solid for what I've been doing.

**Comment by HalosGhost** [comment]
Changes added to correctly cast each event inside `switch`.

**Comment by sdhand** [comment]
Was there anything else you wanted to do? Or am I OK to merge? Thanks for all your work by the way.

**Comment by HalosGhost** [comment]
I want to walk through `win_xcb.c` once more (hopefully tomorrow) and clean it up a bit in similar ways as I did the other files before this behemoth gets merged :)

Also, I am more than happy to help! This is a really fun project, and I would like to see it reach a really stable and usable point.

**Comment by HalosGhost** [comment]
@sdhand, this most recent one (and the next one I have planned) are perhaps a little more controversial. Tl;dr: instead of defining a bunch of functions that all do the same thing with a very small change, define a macro to declare a function which takes an argument that specifies the difference, and then call the macro a couple of times to declare each function.

It allows for much less repetition (and for changes to be simply applied across all the related functions with one change, which is quite nice); but some people do not like macros.

**Comment by sdhand** [comment]
This sounds great to me. I was trying to think of way of achieving something like this when writing it in the first place, but I didn't know enough about C macros to be able to come up with this solution.

**Comment by HalosGhost** [comment]
I have a clarifying question. In some of the setters, you have used `xcb_configure_window()` and in others, you use `xcb_change_window_attributes()`. As far as I can tell from the man pages, the main difference is that the latter allows you to handle error-handling more manually (which, as far as I can tell, is not done in this repository). Is there another reason for using the later ever rather than always using the former?

**Comment by sdhand** [comment]
`xcb_configure_window()` is for changing the window geometry and "physical properties" if you will. (From the documentation page: "Configures a window’s size, position, border width and stacking order.") `xcb_change_window_attributes()` is for just about everything else. This page lists the attributes that `xcb_change_window_attributes()` allows you to change: http://www.x.org/releases/current/doc/man/man3/xcb_change_window_attributes.3.xhtml

**Comment by HalosGhost** [comment]
Good to know! I likely need to make a few changes to the first set of macro modifications (but I'm going to hopefully make them to be even more general so I can generate more code.

**Comment by HalosGhost** [comment]
I was hoping I could generalize the macros so that `raise`, `lower`, `subscribe` and `unsubscribe` could be generated from the same ones, but this is not really doable without an API change. I can still generate them with a macro, of course, but it would be a new one, and the resulting difference in code is ~4 fewer sloc (i.e., I do not think moving them to a macro simplifies much without the API change—which, even if you are interested in, should not be in this PR).

At this point, I am ready for the PR to be merged. Just let me know if you see something broken first and I will take care of it!

**Comment by HalosGhost** [comment]
@sdhand, the last change allowed me to add `lower` and `raise` to the generated setters without an API break (I just added `lower` and `raise` as convenience macro shortcuts to the new setter—which means that no other code needed to change). This is an API change since a new function was added, though, so that should be considered.

I looked into converting `subscribe` and `unsubscribe` in this fashion, but it looks like because setters all `xcb_flush(conn)`, that may not be possible.

**Comment by sdhand** [comment]
I'm fairly sure `subscribe()` and `unsubscribe()` should actually call xcb_flush(conn), and omitting that is just an oversight on my part. Feel free to use a macro for them. Also, I think you should be able to add `get_border_width()` as a getter as it works pretty much identically to all the other getters.

**Comment by HalosGhost** [comment]
@sdhand, I tried adding `subscribe()` and `unsubscribe()` similar to `lower()`/`raise()` and `cat`ing out `event` seems to not work anymore. I will look into it further to see if it will work. and I will look into adding `get_border_width()` as a getter as well.

**Comment by HalosGhost** [comment]
@sdhand, all right; that works for both afterall (I don't know what went wrong in my last test).

**Comment by sdhand** [comment]
This is looking great, do you have anything left you want to do before I merge? I'll give it a quick test before I do, but currently the only commit I have any issue with is https://github.com/sdhand/x11fs/pull/1/commits/f45b7685d0ef59f761428cbdf447cebf9ab1baa0 . Personally I think it's much easier to tell what's going on with the ternary operator.

**Comment by HalosGhost** [comment]
Nope, that's all. The motivation behind that commit is that it is a lot faster (but branchless alternatives can often be less clear).

Note though that there's a lot more I'd like to do, I just think they belong better in another PR.

**Pull request merged**
